using CodeCasa.AutoGenerated;

namespace CodeCasa.CustomEntities.GoogleHome
{
    public class GoogleHomeTimerEntities(SensorEntities sensorEntities) : IEnumerable<SensorEntity>
    {
        public IEnumerator<SensorEntity> GetEnumerator()
        {
            yield return sensorEntities.KitchenSpeakerTimers;
            yield return sensorEntities.LivingRoomSpeakerTimers;
            yield return sensorEntities.OfficeSpeakerTimers;
        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
    }
}
