using CodeCasa.AutoGenerated.Extensions;
using CodeCasa.NetDaemon.Utilities.Extensions;

namespace CodeCasa.Dashboard.Extensions;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddCodeCasa(this IServiceCollection serviceCollection)
    {
        return serviceCollection
            .AddHomeAssistantGenerated()
            .AddNetDaemonConnectionUtils();
    }
}