using CodeCasa.AutoGenerated.Extensions;
using CodeCasa.CustomEntities.Extensions;
using NetDaemon.RuntimeState.Extensions;

namespace CodeCasa.Dashboard.Extensions;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddCodeCasa(this IServiceCollection serviceCollection)
    {
        return serviceCollection
            .AddHomeAssistantGenerated()
            .AddNetDaemonRuntimeStateService()
            .AddCodeCasaCustomFrontEndEntities();
    }
}