using CodeCasa.AutoGenerated.Extensions;

namespace CodeCasa.Dashboard.Extensions;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddCodeCasa(this IServiceCollection serviceCollection)
    {
        return serviceCollection.AddCodeCasaEntities();
    }
}