using CodeCasa.AutoGenerated;
using CodeCasa.NetDaemon.Utilities.Entities;

namespace CodeCasa.CustomEntities.Core.Weather;

public record ForecastHome : TypeSafeWeatherEntity
{
    public ForecastHome(WeatherEntities weatherEntities) 
        : base(weatherEntities.ForecastHome)
    {
    }
}