using NetDaemon.PhoneNotifications.Config;
using CodeCasa.AutoGenerated;
using CodeCasa.CustomEntities.Phones;

namespace CodeCasa.CustomEntities.People
{
    public class Jasper : CompositePersonEntity<AndroidNotificationConfig, AndroidNotificationAction>
    {
        public Jasper(
            InputSelectEntities inputSelectEntities,
            PersonEntities personEntities,
            PhoneJasper phoneJasper) 
            : base("Jasper",
                Genders.Male,
                inputSelectEntities.JasperState, 
                personEntities.Jasper, 
                phoneJasper)
        {
        }
    }
}
