using CodeCasa.AutoGenerated;
using NetDaemon.HassModel;
using NetDaemon.PhoneNotifications;

namespace CodeCasa.CustomEntities.Notifications.Phones;

public class JanePhoneNotifications(NotifyServices notificationServices, IHaContext haContext)
    : PhoneNotificationEntity(haContext, notificationServices.MobileAppIphoneVanJane);