using CodeCasa.AutoGenerated;
using NetDaemon.HassModel;
using NetDaemon.Notifications.Phone;

namespace CodeCasa.CustomEntities.Notifications.Phones;

public class JanePhoneNotifications(NotifyServices notificationServices, IHaContext haContext)
    : PhoneNotificationEntity(haContext, notificationServices.MobileAppIphoneVanJane);