using Microsoft.Extensions.DependencyInjection;

namespace CodeCasa.AutoGenerated.Extensions;

public static class GeneratedExtensions
{
    ///<summary>Registers all injectable generated types in the serviceCollection</summary>
    public static IServiceCollection AddHomeAssistantGenerated(this IServiceCollection serviceCollection)
    {
        return serviceCollection
            .AddTransient<Entities>()
            .AddTransient<CoverEntities>()
            .AddTransient<InputSelectEntities>()
            .AddTransient<LightEntities>()
            .AddTransient<PersonEntities>()
            .AddTransient<NotifyServices>();
    }
}