using Microsoft.Extensions.DependencyInjection;

namespace CodeCasa.AutoGenerated.Extensions;

public static class GeneratedExtensions
{
    ///<summary>Registers all injectable generated types in the serviceCollection</summary>
    public static IServiceCollection AddCodeCasaEntities(this IServiceCollection serviceCollection)
    {
        serviceCollection.AddTransient<Entities>();
        serviceCollection.AddTransient<CoverEntities>();
        serviceCollection.AddTransient<LightEntities>();
        return serviceCollection;
    }
}