using CodeCasa.AutoGenerated;
using CodeCasa.CustomEntities.Automation.Notifications.Dashboards;
using CodeCasa.CustomEntities.Automation.Notifications.Phones;
using CodeCasa.CustomEntities.Core.InputSelect;

namespace CodeCasa.CustomEntities.Automation.People;

public class Jane(
    InputSelectEntities inputSelectEntities,
    PersonEntities personEntities,
    JaneDashboardNotifications janeDashboardNotifications,
    JanePhoneNotifications janePhoneNotifications)
    : CompositePersonEntity("Jane",
        Genders.Female,
        new PersonStateEntity(inputSelectEntities.JaneDoeState),
        personEntities.JaneDoe,
        janeDashboardNotifications,
        janePhoneNotifications);