using CodeCasa.AutoGenerated;
using CodeCasa.CustomEntities.Automation.Notifications.Dashboards;
using CodeCasa.CustomEntities.Automation.Notifications.Phones;
using CodeCasa.CustomEntities.Core.InputSelect;
using CodeCasa.NetDaemon.Utilities.Entities;

namespace CodeCasa.CustomEntities.Automation.People;

public class Jane(
    InputSelectEntities inputSelectEntities,
    PersonEntities personEntities,
    JaneDashboardNotifications janeDashboardNotifications,
    JanePhoneNotifications janePhoneNotifications)
    : CompositePersonEntity("Jane",
        Genders.Female,
        new PersonStateEntity(inputSelectEntities.JaneDoeState),
        new TypeSafePersonEntity(personEntities.JaneDoe),
        janeDashboardNotifications,
        janePhoneNotifications);