using CodeCasa.AutoGenerated;
using CodeCasa.CustomEntities.Automation.Notifications.Dashboards;
using CodeCasa.CustomEntities.Automation.Notifications.Phones;
using CodeCasa.CustomEntities.Core.InputSelect;
using CodeCasa.NetDaemon.Utilities.Entities;

namespace CodeCasa.CustomEntities.Automation.People;

public class Jasper(
    InputSelectEntities inputSelectEntities,
    PersonEntities personEntities,
    JasperDashboardNotifications jasperDashboardNotifications,
    JasperPhoneNotifications jasperPhoneNotifications)
    : CompositePersonEntity("Jasper",
        Genders.Male,
        new PersonStateEntity(inputSelectEntities.JasperState),
        new TypeSafePersonEntity(personEntities.Jasper),
        jasperDashboardNotifications,
        jasperPhoneNotifications);