using CodeCasa.AutoGenerated;
using CodeCasa.CustomEntities.Automation.Notifications.Dashboards;
using CodeCasa.CustomEntities.Automation.Notifications.Phones;
using CodeCasa.CustomEntities.Core.InputSelect;

namespace CodeCasa.CustomEntities.Automation.People;

public class Jasper(
    InputSelectEntities inputSelectEntities,
    PersonEntities personEntities,
    JasperDashboardNotifications jasperDashboardNotifications,
    JasperPhoneNotifications jasperPhoneNotifications)
    : CompositePersonEntity("Jasper",
        Genders.Male,
        new PersonStateEntity(inputSelectEntities.JasperState),
        personEntities.Jasper,
        jasperDashboardNotifications,
        jasperPhoneNotifications);