using CodeCasa.AutoGenerated;
using CodeCasa.CustomEntities.Automation.People;
using CodeCasa.NetDaemon.Utilities.Entities;

namespace CodeCasa.CustomEntities.Core.InputSelect;

public record PersonStateEntity : TypeSafeInputSelectEntity<PersonStates>
{
    public PersonStateEntity(InputSelectEntity inputSelectEntity)
        : base(inputSelectEntity)
    {
    }
}