using AutomationPipelines.Extensions;
using CodeCasa.AutoGenerated.Extensions;
using CodeCasa.CustomEntities.Extensions;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using NetDaemon.InputSelectNotifications.Extensions;
using Occurify.Astro;

namespace CodeCasa.Automations.Extensions;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddCodeCasa(this IServiceCollection serviceCollection, IConfiguration configuration)
    {
        // Setting coordinates for the whole application to use.
        Coordinates.Local = new Coordinates(52.374191, 4.912269, 2.5);

        return serviceCollection
            .AddAutomationPipelines()
            .AddHomeAssistantGenerated()
            .AddCodeCasaCustomEntities()
            .AddInputSelectNotifications(configuration);
    }
}