using CodeCasa.AutoGenerated.Extensions;
using CodeCasa.Pipeline.Extensions;
using Microsoft.Extensions.DependencyInjection;

namespace CodeCasa.Automations.Extensions
{
    public static class ServiceCollectionExtensions
    {
        public static IServiceCollection AddCodeCasa(this IServiceCollection serviceCollection)
        {
            return serviceCollection
                .AddCodeCasaEntities()
                .AddCodeCasaPipeline();
        }
    }
}
