using CodeCasa.AutoGenerated.Parameters;

namespace CodeCasa.NetDaemon.Utilities.Extensions;

internal static class LightParametersExtensions
{
    public static LightTurnOnParameters ToLightTurnOnParameters(this LightParameters lightParameters)
    {
        return new LightTurnOnParameters
        {
            Transition = lightParameters.Transition?.TotalSeconds,
            Brightness = lightParameters.Brightness,
            RgbColor = lightParameters.RgbColor?.ToRgbCollection(),
            ColorTemp = lightParameters.ColorTemp
        };
    }

    public static LightTurnOffParameters ToLightTurnOffParameters(this LightParameters lightParameters)
    {
        return new LightTurnOffParameters
        {
            Transition = lightParameters.Transition?.TotalSeconds
        };
    }
}