using NetDaemon.PhoneNotifications.Config;
using CodeCasa.AutoGenerated;
using CodeCasa.CustomEntities.Phones;

namespace CodeCasa.CustomEntities.People
{
    public class Jane : CompositePersonEntity<IosNotificationConfig, IosNotificationAction>
    {
        public Jane(
            InputSelectEntities inputSelectEntities,
            PersonEntities personEntities,
            PhoneJane phoneJane) 
            : base("Jane",
                Genders.Female,
                inputSelectEntities.JaneDoeState, 
                personEntities.JaneDoe, 
                phoneJane)
        {
        }
    }
}
