using CodeCasa.AutoGenerated;
using CodeCasa.CustomEntities.Notifications.Dashboards;
using CodeCasa.CustomEntities.Notifications.Phones;

namespace CodeCasa.CustomEntities.People;

public class Jasper(
    InputSelectEntities inputSelectEntities,
    PersonEntities personEntities,
    JasperDashboardNotifications jasperDashboardNotifications,
    JasperPhoneNotifications jasperPhoneNotifications)
    : CompositePersonEntity("Jasper",
        Genders.Male,
        inputSelectEntities.JasperState,
        personEntities.Jasper,
        jasperDashboardNotifications,
        jasperPhoneNotifications);