using System.Reactive.Concurrency;
using CodeCasa.AutoGenerated;

namespace CodeCasa.Automations.Apps.Lights.BackyardLights;

public class BackyardStringLightsEnergySavingNode(CoverEntities coverEntities, IScheduler scheduler)
    : BackyardLightsEnergySavingNode<bool>(coverEntities, false, scheduler);