using System.Reactive.Concurrency;
using CodeCasa.AutoGenerated;
using CodeCasa.NetDaemon.Utilities;

namespace CodeCasa.Automations.Apps.Lights.BackyardLights;

public class BackyardCoachLightsEnergySavingNode(CoverEntities coverEntities, IScheduler scheduler)
    : BackyardLightsEnergySavingNode<LightParameters>(coverEntities, LightParameters.Off(), scheduler);