using CodeCasa.AutoGenerated;
using NetDaemon.HassModel;
using NetDaemon.HassModel.Entities;

namespace CodeCasa.NetDaemon.Utilities.Entities;

public record TypeSafeInputSelectEntity<T> : EnumEntity<T, TypeSafeInputSelectEntity<T>, EnumEntityState<T, InputSelectAttributes>, InputSelectAttributes>, IInputSelectEntityCore 
    where T : struct, Enum
{
    public TypeSafeInputSelectEntity(IHaContext haContext, string entityId) : base(haContext, entityId)
    {
    }

    public TypeSafeInputSelectEntity(IEntityCore entity) : base(entity)
    {
    }
}