using CodeCasa.AutoGenerated;

namespace CodeCasa.CustomEntities.Core.GoogleHome
{
    public class GoogleHomeAlarmEntities(SensorEntities sensorEntities) : IEnumerable<SensorEntity>
    {
        public IEnumerator<SensorEntity> GetEnumerator()
        {
            yield return sensorEntities.KitchenSpeakerAlarms;
            yield return sensorEntities.LivingRoomSpeakerAlarms;
            yield return sensorEntities.OfficeSpeakerAlarms;
        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
    }
}
