using CodeCasa.AutoGenerated;
using CodeCasa.NetDaemon.Utilities.Entities;

namespace CodeCasa.CustomEntities.InputSelect;

public record LivingRoomWallPanelView : TypeSafeInputSelectEntity<LivingRoomWallPanelView.LivingRoomWallPanelViewStates>
{
    public LivingRoomWallPanelView(InputSelectEntities inputSelectEntities) 
        : base(inputSelectEntities.VariableLivingRoomWallPanelView)
    {
    }

    public enum LivingRoomWallPanelViewStates
    {
        Idle,
        Home,
        Media
    }
}