using NetDaemon.HassModel;

namespace CodeCasa.AutoGenerated;

public partial class AutomationEntities
{
    private readonly IHaContext _haContext;
    public AutomationEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all automation entities currently registered (at runtime) in Home Assistant as AutomationEntity</summary>
    public IEnumerable<AutomationEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("automation.")).Select(e => new AutomationEntity(e));
    ///<summary>Webhook Living Room Wall Panel Proximity Detected</summary>
    public AutomationEntity WebhookLivingRoomWallPanelProximityDetected => new(_haContext, "automation.webhook_living_room_wall_panel_proximity_detected");
}