using NetDaemon.HassModel;

namespace CodeCasa.AutoGenerated
{
    public partial class CoverEntities
    {
        private readonly IHaContext _haContext;
        public CoverEntities(IHaContext haContext)
        {
            _haContext = haContext;
        }

        /// <summary>Enumerates all cover entities currently registered (at runtime) in Home Assistant as CoverEntity</summary>
        public IEnumerable<CoverEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("cover.")).Select(e => new CoverEntity(e));
        ///<summary>Kitchen roller shutter</summary>
        public CoverEntity KitchenRollerShutter => new(_haContext, "cover.kitchen_roller_shutter");
        ///<summary>Living Room Back Window Curtain</summary>
        public CoverEntity LivingRoomBackWindowCurtain => new(_haContext, "cover.living_room_back_window_curtain");
        ///<summary>Living Room Roller Shutter</summary>
        public CoverEntity LivingRoomRollerShutter => new(_haContext, "cover.living_room_roller_shutter");
    }
}
