using NetDaemon.HassModel;

namespace CodeCasa.AutoGenerated;

public partial class InputNumberEntities
{
    private readonly IHaContext _haContext;
    public InputNumberEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all input_number entities currently registered (at runtime) in Home Assistant as InputNumberEntity</summary>
    public IEnumerable<InputNumberEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("input_number.")).Select(e => new InputNumberEntity(e));
    ///<summary>Jane Notification Count</summary>
    public InputNumberEntity JaneNotificationCount => new(_haContext, "input_number.jane_notification_count");
    ///<summary>Jasper Notification Count</summary>
    public InputNumberEntity JasperNotificationCount => new(_haContext, "input_number.jasper_notification_count");
}