using NetDaemon.HassModel;
using System.Text.Json.Serialization;

namespace CodeCasa.AutoGenerated
{
    public partial class NotifyServices
    {
        private readonly IHaContext _haContext;
        public NotifyServices(IHaContext haContext)
        {
            _haContext = haContext;
        }

        ///<summary>Sends a notification message using the mobile_app_pixel_7 integration.</summary>
        public void MobileAppPixel7(NotifyMobileAppPixel7Parameters data)
        {
            _haContext.CallService("notify", "mobile_app_pixel_7", null, data);
        }

        ///<summary>Sends a notification message using the mobile_app_pixel_7 integration.</summary>
        ///<param name="message"> eg: The garage door has been open for 10 minutes.</param>
        ///<param name="title"> eg: Your Garage Door Friend</param>
        ///<param name="target"> eg: platform specific</param>
        ///<param name="data"> eg: platform specific</param>
        public void MobileAppPixel7(string message, string? title = null, object? target = null, object? data = null)
        {
            _haContext.CallService("notify", "mobile_app_pixel_7", null, new NotifyMobileAppPixel7Parameters { Message = message, Title = title, Target = target, Data = data });
        }

        ///<summary>Sends a notification message using the mobile_app_iphone_van_jane integration.</summary>
        public void MobileAppIphoneVanJane(NotifyMobileAppIphoneVanJaneParameters data)
        {
            _haContext.CallService("notify", "mobile_app_iphone_van_jane", null, data);
        }

        ///<summary>Sends a notification message using the mobile_app_iphone_van_jane integration.</summary>
        ///<param name="message"> eg: The garage door has been open for 10 minutes.</param>
        ///<param name="title"> eg: Your Garage Door Friend</param>
        ///<param name="target"> eg: platform specific</param>
        ///<param name="data"> eg: platform specific</param>
        public void MobileAppIphoneVanJane(string message, string? title = null, object? target = null, object? data = null)
        {
            _haContext.CallService("notify", "mobile_app_iphone_van_jane", null, new NotifyMobileAppIphoneVanJaneParameters { Message = message, Title = title, Target = target, Data = data });
        }
    }

    public partial record NotifyMobileAppIphoneVanJaneParameters
    {
        ///<summary> eg: The garage door has been open for 10 minutes.</summary>
        [JsonPropertyName("message")]
        public string? Message { get; init; }

        ///<summary> eg: Your Garage Door Friend</summary>
        [JsonPropertyName("title")]
        public string? Title { get; init; }

        ///<summary> eg: platform specific</summary>
        [JsonPropertyName("target")]
        public object? Target { get; init; }

        ///<summary> eg: platform specific</summary>
        [JsonPropertyName("data")]
        public object? Data { get; init; }
    }

}
