using NetDaemon.HassModel;

namespace CodeCasa.AutoGenerated;

public partial class PersonEntities
{
    private readonly IHaContext _haContext;
    public PersonEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all person entities currently registered (at runtime) in Home Assistant as PersonEntity</summary>
    public IEnumerable<PersonEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("person.")).Select(e => new PersonEntity(e));
    ///<summary>Jane</summary>
    public PersonEntity JaneDoe => new(_haContext, "person.jane");
    ///<summary>Jasper</summary>
    public PersonEntity Jasper => new(_haContext, "person.jasper");
}