using NetDaemon.HassModel;

namespace CodeCasa.AutoGenerated;

public partial class SensorEntities
{
    private readonly IHaContext _haContext;

    public SensorEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all numeric sensor entities currently registered (at runtime) in Home Assistant as NumericSensorEntity</summary>
    public IEnumerable<NumericSensorEntity> EnumerateAllNumeric() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("sensor.") && (e.EntityState?.AttributesJson?.TryGetProperty("unit_of_measurement", out _) ?? false)).Select(e => new NumericSensorEntity(e));

    ///<summary>Living Room Temperature</summary>
    public NumericSensorEntity LivingRoomTemperature => new(_haContext, "sensor.living_room_temperature");
}