using CodeCasa.AutoGenerated;
using NetDaemon.HassModel;
using NetDaemon.PhoneNotifications;

namespace CodeCasa.CustomEntities.Phones;

public class PhoneJasper(NotifyServices notificationServices, IHaContext haContext)
    : PhoneNotificationEntity(haContext, notificationServices.MobileAppPixel7);