using CodeCasa.AutoGenerated;
using NetDaemon.HassModel;
using NetDaemon.PhoneNotifications;

namespace CodeCasa.CustomEntities.Phones;

public class PhoneJane(NotifyServices notificationServices, IHaContext haContext)
    : PhoneNotificationEntity(haContext, notificationServices.MobileAppIphoneVanJane);