using CodeCasa.AutoGenerated;
using NetDaemon.HassModel;
using NetDaemon.PhoneNotifications;

namespace CodeCasa.CustomEntities.Phones
{
    public class PhoneJasper(NotifyServices notificationServices, IHaContext haContext) : PhoneNotificationEntity(haContext)
    {
        protected override void NotificationServiceNotifyImplementation(string message, string? title, object? data)
        {
            notificationServices.MobileAppPixel7(message, title, data: data);
        }
    }
}
