name: 🛠️ CI Build & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: 🗂️ Checkout the repository
        uses: actions/checkout@main

      - name: ⬇️ Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: 🛠️ Build code
        run: dotnet build --configuration Release -p:TreatWarningsAsErrors=true