using CodeCasa.AutoGenerated;
using CodeCasa.CustomEntities.Events;
using Microsoft.Extensions.DependencyInjection;
using NetDaemon.AppModel;
using NetDaemon.HassModel;
using NetDaemon.InputSelectNotifications.Config;
using NetDaemon.InputSelectNotifications.Interact;
using System.Drawing;
using System.Reactive.Linq;
using NetDaemon.InputSelectNotifications;

namespace CodeCasa.Automations.Apps.Notifications;

[NetDaemonApp]
internal class DemoNotifications
{
    private List<InputSelectNotification> _notifications = new();
    private int _manuallyAddedIndex;

    public DemoNotifications(
        IHaContext haContext,
        LightEntities lightEntities, 
        [FromKeyedServices("input_select.living_room_panel_notifications")] IInputSelectNotificationEntity inputSelectNotifications)
    {
        haContext.Events.Where(e => e.EventType == Events.AddDemoNotificationEvent).Subscribe(_ =>
        {
            _notifications.Clear();
            _manuallyAddedIndex = 0;

            var clickToRemoveNotificationId = $"{nameof(DemoNotifications)}_ClickToRemove";
            var clickToUndoRemoveNotificationId = $"{nameof(DemoNotifications)}_ClickToUndoRemove";

            void AddClickToRemoveNotificationAction() =>
                _notifications.Add(inputSelectNotifications.Notify(new InputSelectNotificationConfig
                {
                    Message = "Demo Notification 1",
                    SecondaryMessage = "Click to remove me.",
                    Icon = "Icons.Material.Filled.AutoAwesome",
                    IconColor = Color.Yellow,
                    BadgeIcon = "Icons.Material.Filled.Delete",
                    BadgeIconColor = Color.Red,
                    Action = () =>
                    {
                        inputSelectNotifications.RemoveNotification(clickToRemoveNotificationId);
                        _notifications = _notifications.Where(n => n.Id != clickToRemoveNotificationId).ToList();

                        _notifications.Add(inputSelectNotifications.Notify(new InputSelectNotificationConfig
                        {
                            Message = "Notification removed!",
                            SecondaryMessage = "Click to undo remove.",
                            Icon = "Icons.Material.Filled.Undo",
                            IconColor = Color.Green,
                            Timeout = TimeSpan.FromSeconds(3),
                            Action = () =>
                            {
                                inputSelectNotifications.RemoveNotification(clickToUndoRemoveNotificationId);
                                _notifications = _notifications.Where(n => n.Id != clickToUndoRemoveNotificationId).ToList();

                                AddClickToRemoveNotificationAction();
                            }
                        }, clickToUndoRemoveNotificationId));
                    }
                }, clickToRemoveNotificationId));
            AddClickToRemoveNotificationAction();

            var clearNotificationId = $"{nameof(DemoNotifications)}_Clear";
            _notifications.Add(inputSelectNotifications.Notify(new InputSelectNotificationConfig
            {
                Message = "Demo Notification 2",
                SecondaryMessage = "Click to clear demo notifications.",
                Icon = "Icons.Material.Filled.AutoAwesome",
                IconColor = Color.Yellow,
                BadgeIcon = "Icons.Material.Filled.DeleteForever",
                BadgeIconColor = Color.Red,
                Action = () =>
                {
                    foreach (var notification in _notifications)
                    {
                        inputSelectNotifications.RemoveNotification(notification);
                    }

                    _notifications.Clear();
                }
            }, clearNotificationId));

            var addNotificationNotificationId = $"{nameof(DemoNotifications)}_Add";
            void AddNotificationNotificationAction() => _notifications.Add(inputSelectNotifications.Notify(new InputSelectNotificationConfig
            {
                Message = "Demo Notification 3",
                SecondaryMessage = "Click to add notification.",
                Icon = "Icons.Material.Filled.AutoAwesome",
                IconColor = Color.Yellow,
                BadgeIcon = _manuallyAddedIndex == 0 ? "Icons.Material.Filled.Add" : null,
                BadgeIconColor = Color.Green,
                BadgeContent = _manuallyAddedIndex == 0 ? null : $"{_manuallyAddedIndex}",
                Action = () =>
                {
                    _manuallyAddedIndex++;
                    var notificationId = Guid.NewGuid().ToString();
                    _notifications.Add(inputSelectNotifications.Notify(new InputSelectNotificationConfig
                    {
                        Message = $"Added Demo Notification ({_manuallyAddedIndex})",
                        SecondaryMessage = "Click to remove me.",
                        Icon = "Icons.Material.Filled.AutoAwesome",
                        IconColor = Color.Orange,
                        BadgeContent = $"{_manuallyAddedIndex}",
                        Action = () =>
                        {
                            inputSelectNotifications.RemoveNotification(notificationId);
                            _notifications = _notifications.Where(n => n.Id != notificationId).ToList();
                        }
                    }, notificationId));
                    AddNotificationNotificationAction();
                }
            }, addNotificationNotificationId));

            AddNotificationNotificationAction();
        });
    }
}