using CodeCasa.AutoGenerated;
using CodeCasa.CustomEntities.People;
using NetDaemon.AppModel;
using NetDaemon.Extensions.Observables;
using NetDaemon.PhoneNotifications.Config;

namespace CodeCasa.Automations.Apps.Notifications
{
    [NetDaemonApp]
    internal class NotificationWhenOfficeLightsAreOn
    {
        public NotificationWhenOfficeLightsAreOn(LightEntities lightEntities, Jasper jasper)
        {
            var notificationId = $"{nameof(NotificationWhenOfficeLightsAreOn)}_Notification"; // Using an ID that is consistent between runs also ensures that old notifications are removed/replaced when the app is reloaded.
            lightEntities.OfficeLights.SubscribeOnOff(
                () => jasper.Phone.Notify(new AndroidNotificationConfig
                {
                    Message = $"Hey {jasper.Name}, the office lights are on!"
                }, notificationId), 
                () => jasper.Phone.RemoveNotification(notificationId));
        }
    }
}
